const path = require("path")

exports.createPages = async ({ graphql, actions, reporter }) => {
  // Destructure the createPage function from the actions object
  const { createPage } = actions

  const result = await graphql(`
    query projectsIndexQuery {
      allMdx {
        edges {
          node {
            id
            slug
            frontmatter {
              title
            }
          }
        }
      }
    }
  `)
  if (result.errors) {
    reporter.panicOnBuild('🚨  ERROR: Loading "createPages" query')
  }
  // Create blog post pages.
  const projects = result.data.allMdx.edges
  // you'll call `createPage` for each result
  // console.log("Projects")
  // console.log(projects)

  projects.forEach(({ node }, index) => {
    // console.log("Node:")
    // console.log(node)
    // Blog Post

    // Article
    // console.log("Creating Project Page...")

    // Project

    createPage({
      // The slug generated by gatsby-plugin-mdx doesn't contain a slash at the beginning
      // You can prepend it with any prefix you want
      path: `/projects/${node.slug}`,
      // This component will wrap our MDX projects
      component: path.resolve(`./src/layouts/projects-page-layout.js`),
      // You can use the values in this context in
      // our page layout component
      context: { id: node.id },
    })
  })
}
